name: Node.js CI

on:
  push:
    branches: ["main"]
    

  
jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        run:  sudo actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        run: |
          sudo apt-get update 
          sudo apt-get install -y nodejs
          sudo npm install -g npm
